name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actonlang/setup-acton@v1
        with:
          channel: 'tip'
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - run: acton test --min-time 1000
